# Release pipeline

pr: none
trigger: none

pool: '1ES-Host-Ubuntu'

workspace:
  clean: all

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
      checkLatest: true
    displayName: 'Install Node.js'

  - script: yarn install --frozen-lockfile
    displayName: Install dependencies

  - script: yarn nx run-many --target=build --all --parallel --max-parallel=3
    displayName: Build artifacts

  - script: |
      git config user.name "Fluent UI Build"
      git config user.email "fluentui-internal@service.microsoft.com"
      git remote set-url origin https://$(githubUser):$(githubPAT)@github.com/microsoft/fluentui.git
    displayName: Authenticate git for pushes

  - script: |
      yarn beachball publish -b origin/main --access public -y -n $(npmTokenTmp)
      git reset --hard origin/main
    env:
      GITHUB_PAT: $(githubPAT)
    displayName: Publish to NPM & bump versions
